services:
  prometheus:
    image: prom/prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus_config/:/config
    command:
      - --config.file=/config/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana_config/grafana.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./grafana_config/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana_dashboards:/var/lib/grafana/dashboards
    environment:
      GF_SECURITY_ADMIN_USER: "${GRAFANA_USER}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_PASSWORD}"
      GF_SECURITY_ADMIN_PASSWORD__SKIP_VERIFY: "true"
  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    ports:
      - "9115:9115/tcp"
    volumes:
      - ./blackbox_config/:/config
    command:
      - --config.file=/config/blackbox.yml
    depends_on:
      - prometheus
      
